In [1]:
import pandas as pd 
import numpy as np

In [8]:
# Create dataset 
df = pd.DataFrame({
         "Name": ["Scott", "Mike", "Frank", "James", "Maria", "Linda", "Sarah", "Jane"],
         "Gender": ["Male", "Male", "Male", "Male", "Female", "Female", "Female", "Female"],
         "Income": [3000, 4000, np.nan, np.nan, 2000, np.nan, np.nan, 6000],
         "Degree": ["Non-academic", "Non-academic", "Academic", "Academic",
                    "Non-academic", "Non-academic", "Academic", "Academic"]
     })
df

    Name  Gender  Income        Degree
0  Scott    Male  3000.0  Non-academic
1   Mike    Male  4000.0  Non-academic
2  Frank    Male     NaN      Academic
3  James    Male     NaN      Academic
4  Maria  Female  2000.0  Non-academic
5  Linda  Female     NaN  Non-academic
6  Sarah  Female     NaN      Academic
7   Jane  Female  6000.0      Academic

In [9]:
df.isna().sum()

Name      0
Gender    0
Income    4
Degree    0
dtype: int64

In [10]:
df.isna().mean() * 100

Name       0.0
Gender     0.0
Income    50.0
Degree     0.0
dtype: float64

In [11]:
df.groupby("Degree")["Income"].apply(lambda x: x.isna().mean())

Degree
Academic        0.75
Non-academic    0.25
Name: Income, dtype: float64

In [12]:
df_drop = df.dropna()
df_drop

    Name  Gender  Income        Degree
0  Scott    Male  3000.0  Non-academic
1   Mike    Male  4000.0  Non-academic
4  Maria  Female  2000.0  Non-academic
7   Jane  Female  6000.0      Academic

In [13]:
len(df_drop)

4

In [14]:
df_drop["Income"].mean()

np.float64(3750.0)

In [15]:
overall_mean = df["Income"].mean()
overall_mean

np.float64(3750.0)

In [16]:
df_mean_impute = df.copy()
df_mean_impute["Income"] = df_mean_impute["Income"].fillna(overall_mean)
df_mean_impute

    Name  Gender  Income        Degree
0  Scott    Male  3000.0  Non-academic
1   Mike    Male  4000.0  Non-academic
2  Frank    Male  3750.0      Academic
3  James    Male  3750.0      Academic
4  Maria  Female  2000.0  Non-academic
5  Linda  Female  3750.0  Non-academic
6  Sarah  Female  3750.0      Academic
7   Jane  Female  6000.0      Academic

In [17]:
df_mean_impute.groupby("Degree")["Income"].mean()

Degree
Academic        4312.5
Non-academic    3187.5
Name: Income, dtype: float64

In [18]:

df_group_impute = df.copy()
     
df_group_impute["Income"] = df_group_impute.groupby("Degree")["Income"].transform(
         lambda x: x.fillna(x.mean())
)
     
df_group_impute

    Name  Gender  Income        Degree
0  Scott    Male  3000.0  Non-academic
1   Mike    Male  4000.0  Non-academic
2  Frank    Male  6000.0      Academic
3  James    Male  6000.0      Academic
4  Maria  Female  2000.0  Non-academic
5  Linda  Female  3000.0  Non-academic
6  Sarah  Female  6000.0      Academic
7   Jane  Female  6000.0      Academic

In [19]:
df_group_impute.groupby("Degree")["Income"].mean()

Degree
Academic        6000.0
Non-academic    3000.0
Name: Income, dtype: float64

In [20]:
comparison = pd.DataFrame({
"Original": df["Income"],
"Mean Imputation": df_mean_impute["Income"],
"Group Imputation": df_group_impute["Income"]
})
comparison

   Original  Mean Imputation  Group Imputation
0    3000.0           3000.0            3000.0
1    4000.0           4000.0            4000.0
2       NaN           3750.0            6000.0
3       NaN           3750.0            6000.0
4    2000.0           2000.0            2000.0
5       NaN           3750.0            3000.0
6       NaN           3750.0            6000.0
7    6000.0           6000.0            6000.0